# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "Release"
on:
  pull_request:
  push:
    paths:
      - 'package.json'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [16.x]

    steps:

      - name: Checking out the project
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i -g @vercel/ncc
      - run: npm ci
      - run: npm run all

      - id: releaser
        name: New Version Decider
        uses: thiagodnf/new-version-decider@v0.0.5
        with:
          loader: nodejs
          configurationFile: ./package.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit files # commit the output folder
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git .
          git commit -m "build"


      # - name: Create Release on Github
      #   uses: softprops/action-gh-release@v1
      #   if: ${{steps.releaser.outputs.newVersion == 'true' }}
      #   with:
      #     name: ${{ steps.releaser.outputs.currentVersion }}
      #     tag_name: v${{steps.releaser.outputs.currentVersion}}
      #     # files: "*"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
